version: '2'
services:
  firefox:
    image: selenium/node-firefox:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.14.0-gallium
    ports:
      - "4444:4444"
  search-module:
    image: selenium-docker:latest
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=Chrome
      - HUB_HOST=hub
      - MODULE=searchmodule.xml
    volumes:
      - ./search-result:/a/b/c/test-output